[[redirects]]
  from = "/badges"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/index"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
